### ISSUE TITLE
Asking to port to 1.12.2

### ISSUE THREAD

**Issue by Tschipp** [UnstoppableN/Invasion-mod#2]
Hey, I'm just wondering if the mod is still in development.

If not, I'm offering to fork the repo and work on a port for 1.12.2(or 1.13) This always used to be one of my favorite mods, so I would be sad to see it disappear forever.

If you're ok with me doing this, please let me know! If you're already working on a port or just don't want me porting it, please say so too. But I think many people still like and miss the mod in recent versions.

**Comment by UnstoppableN** [comment]
The mod is no longer under development by me.
(or anyone else that I know of)

It would be nice if you would continue the development.
Let me know how it goes!

**Comment by Tschipp** [comment]
Cool, Thanks!
